kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vault-kube-cloud-credentials-operator-aws
roleRef:
  kind: ClusterRole
  name: vault-kube-cloud-credentials-operator-aws
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: vault-kube-cloud-credentials-operator-aws
    # update with the namespace where the operator is running
    namespace: example
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vault-kube-cloud-credentials-operator-gcp
roleRef:
  kind: ClusterRole
  name: vault-kube-cloud-credentials-operator-gcp
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: vault-kube-cloud-credentials-operator-gcp
    # update with the namespace where the operator is running
    namespace: example
