apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-kube-cloud-credentials-operator
spec:
  template:
    spec:
      containers:
        - name: vault-kube-cloud-credentials-operator
          args:
            - operator
            - -config-file=/etc/vkcc/config.yaml
          env:
            - name: VAULT_ADDR
              value: "https://vault:8200"
            - name: VAULT_CACERT
              value: "/etc/tls/ca.crt"
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault
                  key: root-token
          volumeMounts:
            - name: config
              mountPath: /etc/vkcc
            - name: tls
              mountPath: /etc/tls
      volumes:
        - name: config
          configMap:
            name: vault-kube-cloud-credentials-operator
        - name: tls
          secret:
            secretName: vault-tls
            defaultMode: 0400
