variable "environment" {
  type        = string
  description = <<EOS
This is used as an identifier for vault-generated ServiceAccounts. In the case
of multiple vault deployments operating in the same GCP project, we need a way
to identify SAs generated by a specific vault deployment in order to be able to
cleanup orphans.
EOS
}

variable "kube_namespace" {
  type = string
}

variable "kube_sa_name" {
  type = string
}

variable "gcp_bindings" {
  type = list(object({
    resource = string
    roles    = list(string)
  }))
}

variable "gcp_project" {
  type = string
}

variable "kubernetes_auth_backend" {
  type    = string
  default = "kubernetes"
}

variable "gcp_secret_backend" {
  type    = string
  default = "gcp"
}

variable "token_ttl" {
  type    = number
  default = 900
}
