apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../base
configMapGenerator:
  - name: k8s-sidecar-injector-configs
    behavior: merge
    files:
      - resources/vault-sidecar-aws-gcp.yaml
      - resources/vault-sidecar-aws.yaml
      - resources/vault-sidecar-gcp.yaml
