name: vault-sidecar-aws-gcp-base
prependContainers: true
containers:
  - name: vault-credentials-agent-aws
    image: quay.io/utilitywarehouse/vault-kube-cloud-credentials:0.8.1
    lifecycle:
      postStart:
        exec:
          command:
            - /bin/sh
            - -c
            - |
              while ! nc -w 1 127.0.0.1 8098; do sleep 1; done
    args:
      - sidecar
      - -vault-role=$(VKAC_ENVIRONMENT)_aws_$(POD_NAMESPACE)_$(POD_SERVICE_ACCOUNT)
    env:
      - name: VAULT_CACERT
        value: "/etc/tls/ca.crt"
      - name: VAULT_ADDR
        value: "https://vault.sys-vault:8200"
      - name: POD_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: POD_SERVICE_ACCOUNT
        valueFrom:
          fieldRef:
            fieldPath: spec.serviceAccountName
    ports:
      - name: metrics
        containerPort: 8099
        protocol: TCP
    volumeMounts:
      - name: vault-tls
        mountPath: /etc/tls
  - name: vault-credentials-agent-gcp
    image: quay.io/utilitywarehouse/vault-kube-cloud-credentials:0.8.1
    lifecycle:
      postStart:
        exec:
          command:
            - /bin/sh
            - -c
            - |
              while ! nc -w 1 127.0.0.1 8198; do sleep 1; done
    args:
      - sidecar
      - -vault-role=$(VKAC_ENVIRONMENT)_gcp_$(POD_NAMESPACE)_$(POD_SERVICE_ACCOUNT)
      - -listen-address=127.0.0.1:8198
      - -operational-address=:8199
    env:
      - name: VAULT_CACERT
        value: "/etc/tls/ca.crt"
      - name: VAULT_ADDR
        value: "https://vault.sys-vault:8200"
      - name: POD_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: POD_SERVICE_ACCOUNT
        valueFrom:
          fieldRef:
            fieldPath: spec.serviceAccountName
    ports:
      - name: metrics
        containerPort: 8199
        protocol: TCP
    volumeMounts:
      - name: vault-tls
        mountPath: /etc/tls
env:
  - name: AWS_CONTAINER_CREDENTIALS_FULL_URI
    value: "http://127.0.0.1:8098/credentials"
  - name: GCE_METADATA_HOST
    value: "127.0.0.1:8198"
  - name: GCE_METADATA_ROOT
    value: "127.0.0.1:8198"

volumes:
  - name: vault-tls
    configMap:
      name: vault-tls
