name: vault-sidecar-gcp-base
prependContainers: true
containers:
  - name: vault-credentials-agent
    image: quay.io/utilitywarehouse/vault-kube-cloud-credentials:v0.8.5
    lifecycle:
      postStart:
        exec:
          command:
            - /bin/sh
            - -c
            - |
              while ! nc -w 1 127.0.0.1 8098; do sleep 1; done
    args:
      - sidecar
      - -vault-role=$(VKAC_ENVIRONMENT)_gcp_$(POD_NAMESPACE)_$(POD_SERVICE_ACCOUNT)
    env:
      - name: VAULT_CACERT
        value: "/etc/tls/ca.crt"
      - name: VAULT_ADDR
        value: "https://vault.sys-vault:8200"
      - name: POD_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: POD_SERVICE_ACCOUNT
        valueFrom:
          fieldRef:
            fieldPath: spec.serviceAccountName
    ports:
      - name: metrics
        containerPort: 8099
        protocol: TCP
    volumeMounts:
      - name: vault-tls
        mountPath: /etc/tls
env:
  - name: GCE_METADATA_HOST
    value: "127.0.0.1:8098"
  - name: GCE_METADATA_ROOT
    value: "127.0.0.1:8098"

volumes:
  - name: vault-tls
    configMap:
      name: vault-tls
