apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-kube-cloud-credentials-operator-aws
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-kube-cloud-credentials-operator-aws
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-kube-cloud-credentials-operator-aws
  template:
    metadata:
      labels:
        app: vault-kube-cloud-credentials-operator-aws
    spec:
      serviceAccountName: vault-kube-cloud-credentials-operator-aws
      containers:
        - name: vault-kube-cloud-credentials-operator
          image: quay.io/utilitywarehouse/vault-kube-cloud-credentials:v0.9.1
          args:
            - operator
            - -provider=aws
          resources:
            requests:
              cpu: 10m
              memory: 25Mi
            limits:
              cpu: 500m
              memory: 200Mi
