apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-kube-cloud-credentials-operator-gcp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-kube-cloud-credentials-operator-gcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-kube-cloud-credentials-operator-gcp
  template:
    metadata:
      labels:
        app: vault-kube-cloud-credentials-operator-gcp
    spec:
      serviceAccountName: vault-kube-cloud-credentials-operator-gcp
      containers:
        - name: vault-kube-cloud-credentials-operator
          image: quay.io/utilitywarehouse/vault-kube-cloud-credentials:v0.9.1
          args:
            - operator
            - -provider=gcp
          resources:
            requests:
              cpu: 10m
              memory: 25Mi
            limits:
              cpu: 500m
              memory: 200Mi
